export const GET_LOAD_CONTACT_LIST = 'GET_LOAD_CONTACT_LIST';
export const GET_CONTACT = 'GET_CONTACT';
export const GET_CONTACT_PHOTO = 'GET_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const SEARCH_CONTACT = 'SEARCH_CONTACT';