# Generated by Django 3.1.5 on 2021-02-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlistmodel',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='contactlistmodel',
            name='gender',
        ),
    ]
