# Generated by Django 3.1.5 on 2021-02-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0002_auto_20210211_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlistmodel',
            name='avatar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contactlistmodel',
            name='gender',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
