# Generated by Django 3.1.5 on 2021-02-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0003_auto_20210215_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlistmodel',
            old_name='role',
            new_name='phone',
        ),
    ]
